<?php

/**
 * This is the model base class for the table "tbl_news".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "News".
 *
 * Columns in table "tbl_news" available as properties of the model,
 * followed by relations of table "tbl_news" available as properties of the model.
 *
 * @property integer $id
 * @property integer $category_id
 * @property string $lang
 * @property string $creation_date
 * @property string $change_date
 * @property string $date
 * @property string $title
 * @property string $alias
 * @property string $short_text
 * @property string $full_text
 * @property string $image
 * @property string $link
 * @property string $user_id
 * @property integer $status
 * @property integer $is_protected
 * @property string $keywords
 * @property string $description
 *
 * @property Category $category
 * @property User $user
 */
abstract class BaseNews extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_news';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'News|News', $n);
	}

	public static function representingColumn() {
		return 'creation_date';
	}

	public function rules() {
		return array(
			array('creation_date, change_date, date, title, alias, full_text, keywords, description', 'required'),
			array('category_id, status, is_protected', 'numerical', 'integerOnly'=>true),
			array('lang', 'length', 'max'=>2),
			array('title, keywords, description', 'length', 'max'=>250),
			array('alias', 'length', 'max'=>150),
			array('image, link', 'length', 'max'=>300),
			array('user_id', 'length', 'max'=>10),
			array('short_text', 'safe'),
			array('category_id, lang, short_text, image, link, user_id, status, is_protected', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, category_id, lang, creation_date, change_date, date, title, alias, short_text, full_text, image, link, user_id, status, is_protected, keywords, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'category' => array(self::BELONGS_TO, 'Category', 'category_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category_id' => null,
			'lang' => Yii::t('app', 'Lang'),
			'creation_date' => Yii::t('app', 'Creation Date'),
			'change_date' => Yii::t('app', 'Change Date'),
			'date' => Yii::t('app', 'Date'),
			'title' => Yii::t('app', 'Title'),
			'alias' => Yii::t('app', 'Alias'),
			'short_text' => Yii::t('app', 'Short Text'),
			'full_text' => Yii::t('app', 'Full Text'),
			'image' => Yii::t('app', 'Image'),
			'link' => Yii::t('app', 'Link'),
			'user_id' => null,
			'status' => Yii::t('app', 'Status'),
			'is_protected' => Yii::t('app', 'Is Protected'),
			'keywords' => Yii::t('app', 'Keywords'),
			'description' => Yii::t('app', 'Description'),
			'category' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('lang', $this->lang, true);
		$criteria->compare('creation_date', $this->creation_date, true);
		$criteria->compare('change_date', $this->change_date, true);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('alias', $this->alias, true);
		$criteria->compare('short_text', $this->short_text, true);
		$criteria->compare('full_text', $this->full_text, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('link', $this->link, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('is_protected', $this->is_protected);
		$criteria->compare('keywords', $this->keywords, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}