<?php

/**
 * This is the model base class for the table "tbl_category".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Category".
 *
 * Columns in table "tbl_category" available as properties of the model,
 * followed by relations of table "tbl_category" available as properties of the model.
 *
 * @property integer $id
 * @property integer $parent_id
 * @property string $alias
 * @property string $lang
 * @property string $name
 * @property string $image
 * @property string $short_description
 * @property string $description
 * @property integer $status
 *
 * @property Category $parent
 * @property Category[] $categories
 * @property News[] $news
 * @property Page[] $pages
 */
abstract class BaseCategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_category';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Category|Categories', $n);
	}

	public static function representingColumn() {
		return 'alias';
	}

	public function rules() {
		return array(
			array('alias, name, description', 'required'),
			array('parent_id, status', 'numerical', 'integerOnly'=>true),
			array('alias', 'length', 'max'=>150),
			array('lang', 'length', 'max'=>2),
			array('name, image', 'length', 'max'=>250),
			array('short_description', 'safe'),
			array('parent_id, lang, image, short_description, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, parent_id, alias, lang, name, image, short_description, description, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'parent' => array(self::BELONGS_TO, 'Category', 'parent_id'),
			'categories' => array(self::HAS_MANY, 'Category', 'parent_id'),
			'news' => array(self::HAS_MANY, 'News', 'category_id'),
			'pages' => array(self::HAS_MANY, 'Page', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'parent_id' => null,
			'alias' => Yii::t('app', 'Alias'),
			'lang' => Yii::t('app', 'Lang'),
			'name' => Yii::t('app', 'Name'),
			'image' => Yii::t('app', 'Image'),
			'short_description' => Yii::t('app', 'Short Description'),
			'description' => Yii::t('app', 'Description'),
			'status' => Yii::t('app', 'Status'),
			'parent' => null,
			'categories' => null,
			'news' => null,
			'pages' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('alias', $this->alias, true);
		$criteria->compare('lang', $this->lang, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('short_description', $this->short_description, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}